services:
  web:
    build: .
    command: gunicorn tochly.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    working_dir: /tochly
    volumes:
      - ./tochly:/tochly
      - static_volume:/tochly/static
      - media_volume:/tochly/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    user: celeryuser
    working_dir: /tochly
    volumes:
      - ./tochly:/tochly
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  pgdata:
  static_volume:
    driver: local
  media_volume:
    driver: local
