services:
  web:
    build: .
    command: gunicorn tochly.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    working_dir: /tochly
    volumes:
      - ./tochly:/tochly
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - default
      - tochly_redis_net

  celery:
    build: .
    user: celeryuser
    env_file:
      - .env
    working_dir: /tochly
    volumes:
      - ./tochly:/tochly
    depends_on:
      - db
      - redis
    networks:
      - default
      - tochly_redis_net

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - tochly_redis_net

volumes:
  pgdata:

networks:
  tochly_redis_net:
    external: true
