# Generated by Django 4.2.7 on 2023-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('In a Meeting', 'meeting'), ('Commuting', 'commuting'), ('Working Remotely', 'romote'), ('Sick', 'sick'), ('In Leave', 'leave')], default='', max_length=20, null=True),
        ),
    ]
