# Generated by Django 4.2.7 on 2025-01-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('meeting', 'In a Meeting'), ('commuting', 'Commuting'), ('remote', 'Working Remotely'), ('sick', 'Sick'), ('leave', 'In Leave')], default='', max_length=20, null=True),
        ),
    ]
