# Generated by Django 4.2.7 on 2025-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_display_name_remove_profile_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='utc', max_length=50),
        ),
    ]
