# Generated by Django 4.2.7 on 2024-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_team_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(db_index=True, default='T97I470KA', max_length=10, unique=True),
        ),
    ]
