# Generated by Django 4.2.7 on 2024-05-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_team_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(db_index=True, default='T982VS454', max_length=10, unique=True),
        ),
    ]
