# Generated by Django 4.2.7 on 2024-06-01 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_alter_member_team_alter_team_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.CharField(db_index=True, default=members.utils.generate_team_id, max_length=10, unique=True),
        ),
    ]
