# Generated by Django 4.2.7 on 2024-06-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_user_alter_team_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
