# Generated by Django 4.2.7 on 2024-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='permission',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='member', max_length=10),
        ),
    ]
