# Generated by Django 4.2.7 on 2025-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='permission',
            field=models.CharField(choices=[('owner', 'OWNER'), ('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', max_length=10),
        ),
    ]
