# Generated by Django 4.2.7 on 2025-02-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='permission',
            new_name='role',
        ),
    ]
