# Generated by Django 4.2.7 on 2025-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_permission_member_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_active',
            new_name='online',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='last_updated',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='member',
            name='display_name',
            field=models.CharField(default='Ahmad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('meeting', 'In a Meeting'), ('commuting', 'Commuting'), ('remote', 'Working Remotely'), ('sick', 'Sick'), ('leave', 'In Leave')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', max_length=10),
        ),
    ]
