name: Django CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & start services
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run Django tests
        run: docker-compose exec -T web python manage.py test
